### Loading Library

In [1]:
import numpy as np

### 1. Creating numpy array

In [4]:
# a) array from 1D list

list1 = [2, 4, 6, 8, 10]
arr1 = np.array(list1)

In [6]:
print (arr1)

[ 2  4  6  8 10]


In [11]:
type(arr1)

numpy.ndarray

Arrays are different from List. One can apply vectorised operation on arrays which is not possible in case of Python list.

In [14]:
list1 + 1

TypeError: can only concatenate list (not "int") to list

In [6]:
arr1 + 1

array([ 3,  5,  7,  9, 11])

In [16]:
# b) array from 2D list

list2 = [[9, 0, 4, 6], 
         [4 ,6, 1, 1]]
arr2 = np.array (list2)

In [18]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 1, 1]])

In [20]:
arr2 = np.array(list2, dtype = 'float')

In [22]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 1., 1.]])

In [24]:
# d) converting array type

arr3 = arr2.astype('int')
arr3

array([[9, 0, 4, 6],
       [4, 6, 1, 1]])

In [26]:
# d) Boolean array

arr4 = np.array(list2, dtype = 'bool')
arr4

array([[ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [28]:
# e) Object array

arr5 = np.array([2, 5, 'y', 2], dtype = 'object')
arr5

array([2, 5, 'y', 2], dtype=object)

In [30]:
# f) Converting array to list

lis = arr5.tolist()
lis

[2, 5, 'y', 2]

### 2. Array Dimensions

In [33]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 1., 1.]])

In [35]:
arr2.shape

(2, 4)

In [37]:
arr2.size

8

In [43]:
arr2.dtype

dtype('float64')

In [45]:
arr2.ndim

2

### 3. Reversing rows and columns

In [48]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 1., 1.]])

In [50]:
# reversing rows and columns

arr2[::-1, ::-1]

array([[1., 1., 6., 4.],
       [6., 4., 0., 9.]])

In [52]:
# reversing rows

arr2[::-1, ]

array([[4., 6., 1., 1.],
       [9., 0., 4., 6.]])

### 4. Specific element extraction

In [55]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 1., 1.]])

In [24]:
# ROW 1

arr2[:1, :]

array([[9., 0., 4., 6.]])

In [25]:
# Rows 

arr2[:2, :]

array([[9., 0., 4., 6.],
       [4., 6., 1., 1.]])

In [57]:
# Columns

arr2[:, -1]

array([6., 1.])

In [59]:
arr2[:, 0:3]

array([[9., 0., 4.],
       [4., 6., 1.]])

### 5. Basic Statistics


In [62]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 1., 1.]])

In [64]:
arr2.min()

0.0

In [66]:
arr2.max()

9.0

In [68]:
arr2.sum()

31.0

In [86]:
arr2.mean()

3.875

In [88]:
np.median(arr2)

4.0

In [90]:
np.average(arr2)

3.875

In [92]:
np.var(arr2)

8.359375

In [94]:
arr2[0]

array([9., 0., 4., 6.])

In [96]:
np.average(arr2[0])

4.75

### 6. Reshaping and Flattening

In [99]:
arr2.shape

(2, 4)

In [101]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 1., 1.]])

In [103]:
a = arr2.reshape(4, 2)
a

array([[9., 0.],
       [4., 6.],
       [4., 6.],
       [1., 1.]])

In [107]:
a = arr2.reshape(1, 1, 8)
a

array([[[9., 0., 4., 6., 4., 6., 1., 1.]]])

In [109]:
a.flatten()

array([9., 0., 4., 6., 4., 6., 1., 1.])

### 7. Creating Random arrays and sequences

In [112]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
np.arange(2, 10, 3)

array([2, 5, 8])

In [118]:
np.arange(10, 0)

array([], dtype=int32)

In [120]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [122]:
np.linspace(start=1, stop = 10, num = 3)

array([ 1. ,  5.5, 10. ])

In [124]:
np.linspace(start=1, stop = 10, num = 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [126]:
np.linspace(start=1, stop = 10, num = 4)

array([ 1.,  4.,  7., 10.])

In [128]:
np.zeros([10, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [130]:
np.zeros([2, 3, 4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### 8. Unique items and count

In [133]:
arr = [[1, 4, 5, 2 ,2, 5], 
       [4, 4, 1, 7, 4, 5]]

In [135]:
arr

[[1, 4, 5, 2, 2, 5], [4, 4, 1, 7, 4, 5]]

In [137]:
np.unique(arr, return_counts = True)

(array([1, 2, 4, 5, 7]), array([2, 2, 4, 3, 1], dtype=int64))

In [139]:
unique_values, count_of_values = np.unique(arr, return_counts = True)

In [141]:
unique_values

array([1, 2, 4, 5, 7])

In [143]:
count_of_values

array([2, 2, 4, 3, 1], dtype=int64)

In [145]:
unique_values

array([1, 2, 4, 5, 7])

In [149]:
count_of_values

array([2, 2, 4, 3, 1], dtype=int64)